name: Executar Script Python

on:
  schedule:
    - cron: '15 11 * * *'  # Executa a cada 5 minutos  # Executa todos os dias às 12:15 UTC (09:15 Brasília)
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          python main.py
